getunik_bleed_hd_assessment_data:
    settings:
        allowed_assessment_types:
            gvhd:
                - "agvhd-follow-up"
                - "gvhd-activity-assessment"
                - "gvhd-features"
                - "gvhd-late-onset-acute"
                - "gvhd-new-diagnosis"
                - "gvhd-organ-scoring"
                - "gvhd-self-report"
            bleeding:
                - "demo"
                - "bleeding-features"
                - "bsms"
                - "who"
        feature:
            export: true
            allow_custom_assessments: false
