imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_version: "@getunik.bleed_hd_data.version_service"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - GetunikBleedHdAssessmentUIBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: "%kernel.root_dir%/../bin/node"
            node_paths: [ "%kernel.root_dir%/../bin/node_modules/" ]
            apply_to:   "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS User Bundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Getunik\BleedHd\SecurityBundle\Entity\User

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        Getunik\BleedHd\SecurityBundle\Entity\Client
    access_token_class:  Getunik\BleedHd\SecurityBundle\Entity\AccessToken
    refresh_token_class: Getunik\BleedHd\SecurityBundle\Entity\RefreshToken
    auth_code_class:     Getunik\BleedHd\SecurityBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager

fos_rest:
    routing_loader:
        default_format: json
    body_converter:
        enabled: true
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true

getunik_bleed_hd_security:
    auto_token_client:
        id: "%oauth_client_id%"
        secret: "%oauth_client_secret%"
        target_path: /app

getunik_bleed_hd_assessment_data:
    version: "v-0.5.5"
    version_allow_git: true


jms_serializer:
    handlers:
        # Fix basic JavaScript date / time / serialization handling incompatibility
        # https://github.com/schmittjoh/JMSSerializerBundle/issues/395
        datetime:
            default_format: "Y-m-d\TH:i:s.uO" # ISO8601
            default_timezone: "UTC"
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

        # Using auto-detection, the mapping files for each bundle will be
        # expected in the Resources/config/serializer directory.
        #
        # Example:
        # class: My\FooBundle\Entity\User
        # expected path: @MyFooBundle/Resources/config/serializer/Entity.User.(yml|xml|php)
        auto_detection: true

asoc_assetic_angular_js:
    angular_module_name: '$segments[3]'
