imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["score"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ["!score"]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        score:
            type:     stream
            path:     "%kernel.logs_dir%/score.log"
            channels: ["score"]

getunik_bleed_hd_assessment_data:
    version_allow_git: false
