security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_EDITOR: ROLE_READER
        ROLE_ADMIN: ROLE_EDITOR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_management:
            pattern: ^/user
            form_login:
                provider: fos_userbundle
                check_path: /user/login_check
                login_path: /user/login
                default_target_path: /user/profile
                # TODO: success_handler: my.auth_success_handler
            logout:
                path: /user/logout
                target: /user/login
            anonymous: true
            context: secured

        default:
            anonymous: ~
