patient:
    type: rest
    resource: getunik.bleed_hd_data.patient_controller
patientstatus:
    type: rest
    parent: patient
    resource: getunik.bleed_hd_data.patientstatus_controller
assessment:
    type: rest
    parent: patient
    resource: getunik.bleed_hd_data.assessment_controller
response:
    type: rest
    parent: assessment
    resource: getunik.bleed_hd_data.response_controller
