getunik_bleed_hd_assessment_data_homepage:
    path:     /hello2/{name}
    defaults: { _controller: GetunikBleedHdAssessmentDataBundle:Default:index }

getunik_bleed_hd_assessment_data_customers:
    type:     rest
    resource: getunik.bleed_hd_data.patient_controller
