getunik_bleed_hd_assessment_data_patient:
    type: rest
    resource: "@GetunikBleedHdAssessmentDataBundle/Resources/config/patient_routes.yml"

getunik_bleed_hd_assessment_data_questionnaire:
    type: rest
    resource: getunik.bleed_hd_data.questionnaire_controller

getunik_bleed_hd_assessment_data_clientlogentry:
    type: rest
    resource: getunik.bleed_hd_data.clientlogentry_controller

getunik_bleed_hd_assessment_data_user:
    type: rest
    resource: getunik.bleed_hd_data.user_controller

getunik_bleed_hd_assessment_data_export:
    type: rest
    resource: getunik.bleed_hd_data.export_controller
