parameters:
    getunik.bleed_hd_data.patient_controller.class: Getunik\BleedHd\AssessmentDataBundle\Controller\PatientsController
    getunik.bleed_hd_data.patient_manager.class: Getunik\BleedHd\AssessmentDataBundle\Manager\PatientManager


services:
    getunik.bleed_hd_data.patient_manager:
                class: %getunik.bleed_hd_data.patient_manager.class%
                arguments:
                    - @doctrine

    getunik.bleed_hd_data.patient_controller:
                class: %getunik.bleed_hd_data.patient_controller.class%
                arguments:
                    - @getunik.bleed_hd_data.patient_manager
                calls:
                    - [setContainer, ["@service_container"]]
