parameters:
    getunik.bleed_hd_data.entity_manager_service: doctrine.orm.default_entity_manager
    getunik.bleed_hd_data.patient_manager.class: Getunik\BleedHd\AssessmentDataBundle\Manager\PatientManager
    getunik.bleed_hd_data.patient_repository.class: Getunik\BleedHd\AssessmentDataBundle\Entity\PatientRepository
    getunik.bleed_hd_data.patient_controller.class: Getunik\BleedHd\AssessmentDataBundle\Controller\PatientsController
    getunik.bleed_hd_data.patientstatus_repository.class: Getunik\BleedHd\AssessmentDataBundle\Entity\PatientStatusRepository
    getunik.bleed_hd_data.patientstatus_controller.class: Getunik\BleedHd\AssessmentDataBundle\Controller\PatientStatusesController


services:
    getunik.bleed_hd_data.entity_update_listener:
        class: Getunik\BleedHd\AssessmentDataBundle\Listener\UpdateInformationListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    getunik.bleed_hd_data.flush_data_listener:
        class: Getunik\BleedHd\AssessmentDataBundle\Listener\FlushDataListener
        arguments: ['@service_container', '%getunik.bleed_hd_data.entity_manager_service%']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    getunik.bleed_hd_data.patient_manager:
                class: %getunik.bleed_hd_data.patient_manager.class%
                arguments:
                    - @doctrine

    getunik.bleed_hd_data.patient_repository:
        class: %getunik.bleed_hd_data.patient_repository.class%
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - "GetunikBleedHdAssessmentDataBundle:Patient"

    getunik.bleed_hd_data.patientstatus_repository:
        class: %getunik.bleed_hd_data.patientstatus_repository.class%
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - "GetunikBleedHdAssessmentDataBundle:PatientStatus"
        calls:
            - [setSecurityContext, ["@security.context"]]

    getunik.bleed_hd_data.patient_controller:
                class: %getunik.bleed_hd_data.patient_controller.class%
                arguments:
                    - @getunik.bleed_hd_data.patient_repository
                    - @getunik.bleed_hd_data.patient_manager
                calls:
                    - [setContainer, ["@service_container"]]

    getunik.bleed_hd_data.patientstatus_controller:
                class: %getunik.bleed_hd_data.patientstatus_controller.class%
                arguments:
                    - @getunik.bleed_hd_data.patientstatus_repository
                calls:
                    - [setContainer, ["@service_container"]]
