<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssessmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentRepository extends EntityRepository
{
    public function save(Assessment $assessment)
    {
        $this->_em->persist($assessment);
    }

    public function update(Assessment $assessment)
    {
        $merged = $this->_em->merge($assessment);

        return $merged;
    }
}
