<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * AssessmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentRepository extends EntityRepository
{
    public function save(Assessment $assessment, $flush = false)
    {
        $this->_em->persist($assessment);
        if ($flush)
        {
            $this->_em->flush();
        }
    }

    public function update(Assessment $assessment)
    {
        $merged = $this->_em->merge($assessment);

        return $merged;
    }

    public function getPatientProgress(array $patientIds)
    {
        $builder = $this->_em->createQueryBuilder();

        $builder
            ->select('a.patientId, a.progress')
            ->from('GetunikBleedHdAssessmentDataBundle:Assessment', 'a')
            ->where($builder->expr()->in('a.patientId', $patientIds));

        $query = $builder->getQuery();
        $array = $query->getArrayResult();

        return $array;
    }
}
