<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ClientLogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientLogEntryRepository extends EntityRepository
{
    public function save(ClientLogEntry $logEntry, $flush = false)
    {
        $this->_em->persist($logEntry);
        if ($flush)
        {
            $this->_em->flush();
        }
    }
}
