<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
    public function save(Patient $patient, $flush = false)
    {
        $this->_em->persist($patient);
        if ($flush)
        {
            $this->_em->flush();
        }
    }

    public function update(Patient $patient)
    {
        $merged = $this->_em->merge($patient);

        return $merged;
    }
}
