<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PatientStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientStatusRepository extends EntityRepository
{
    public function save(PatientStatus $status, $flush = false)
    {
        $this->_em->persist($status);
        if ($flush)
        {
            $this->_em->flush();
        }
    }

    public function update(PatientStatus $status)
    {
        $merged = $this->_em->merge($status);

        return $merged;
    }
}
