<?php

namespace Getunik\BleedHd\AssessmentDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
    public function save(Response $response)
    {
        $this->_em->persist($response);
    }

    public function update(Response $response)
    {
        $merged = $this->_em->merge($response);

        return $merged;
    }
}
