
name: Default
type: who
columns:
  -
      __directive:
        op: insert
        source: ../patient-default.yaml
  -
      __directive:
        op: insert
        source: ../assessment-default.yaml
  -
      label: Score
      extractor: Score
      reference: total
  -
      # label is optional if same as reference
      label: gvhd-new-diagnosis.chronic.skin.diagnostic
      extractor: Response
      reference: gvhd-new-diagnosis.chronic.skin.diagnostic
  -
      extractor: Response
      reference: gvhd-new-diagnosis.chronic.skin.distinctive
  -
      extractor: Response
      reference: gvhd-new-diagnosis.chronic.skin.other
  -
      extractor: Response
      reference: gvhd-new-diagnosis.chronic.skin.common
