
name: Default
type: who
columns:
  -
      __directive:
        op: insert
        source: ../patient-default.yaml
  -
      __directive:
        op: insert
        source: ../assessment-default.yaml
  -
      label: Score
      extractor: Score
      reference: total
  -
      extractor: Response
      reference: who.mouth-and-nose.petechiae
  -
      extractor: Supplement
      reference: who.mouth-and-nose.petechiae.isnew
  -
      extractor: Response
      reference: who.mouth-and-nose.nose-bleed
  -
      extractor: Supplement
      reference: who.mouth-and-nose.nose-bleed.duration
  -
      extractor: Response
      reference: who.mouth-and-nose.mouth-bleed
  -
      extractor: Supplement
      reference: who.mouth-and-nose.mouth-bleed.duration
  -
      extractor: Response
      reference: who.skin-and-tissue.deep-tissue-hematomas
  -
      extractor: Response
      reference: who.skin-and-tissue.joint-bleeding
  -
      extractor: Response
      reference: who.skin-and-tissue.petechiae
  -
      extractor: Response
      reference: who.skin-and-tissue.skin-hematomas
  -
      extractor: Response
      reference: who.skin-and-tissue.soft-tissue-hematomas
