Getunik\BleedHd\AssessmentDataBundle\Entity\Response:
    exclusion_policy: ALL
    read_only: false
    properties:
        lastUpdatedDate:
            since_version: 1.0
        lastUpdatedBy:
            since_version: 1.0
        assessmentId:
            since_version: 1.0
        questionSlug:
            since_version: 1.0
        result:
            since_version: 1.0
