getunik_bleed_hd_assessment_ui_app:
    path:     /app
    defaults: { _controller: GetunikBleedHdAssessmentUIBundle:Default:index }

getunik_bleed_hd_assessment_ui_root:
    path:     /
    defaults: { _controller: GetunikBleedHdAssessmentUIBundle:Default:rootRedirect }
