
name: GVHD Features Default
type: gvhd-features
columns:
    -
        __directive:
            op: insert
            source: ../patient-default.yaml
    -
        __directive:
            op: insert
            source: ../assessment-default.yaml
    -
        label: Score
        extractor: Score
        reference: total
    # screen 1
    -
        extractor: Response
        reference: gvhd-features.features.features-present
