Getunik\BleedHd\AssessmentDataBundle\Entity\Assessment:
    type:  entity
    table: Assessment
    repositoryClass: Getunik\BleedHd\AssessmentDataBundle\Entity\AssessmentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastUpdatedDate:
            type: datetimetz
            nullable: false
        lastUpdatedBy:
            type: integer
            nullable: false
        createdDate:
            type: datetimetz
            nullable: false
        createdBy:
            type: integer
            nullable: false
        patientId:
            type: integer
            nullable: false
        questionnaire:
            type: string
            length: 255
            nullable: false
        questionnaireVersion:
            type: string
            length: 255
            nullable: true
        startDate:
            type: datetimetz
            nullable: true
        platelets:
            type: float
            nullable: true
        remarks:
            type: text
            nullable: true
        result:
            type: json_array
            nullable: true
        progress:
            type: string
            length: 50
            nullable: true
    oneToMany:
        responses:
            targetEntity: Response
            mappedBy: assessment
    manyToOne:
        patient:
            targetEntity: Patient
            inversedBy: assessments
            joinColumn:
                name: patientId
                referencedColumnName: id
