Getunik\BleedHd\AssessmentDataBundle\Entity\PatientStatus:
    type:  entity
    table: PatientStatus
    repositoryClass: Getunik\BleedHd\AssessmentDataBundle\Entity\PatientStatusRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastUpdatedDate:
            type: datetimetz
            nullable: false
        lastUpdatedBy:
            type: integer
            nullable: false
        patientId:
            type: integer
            nullable: false
        transplantDate:
            type: date
            nullable: true
        transplantType:
            type: string
            length: 255
            nullable: true
        transplantSource:
            type: string
            length: 255
            nullable: true
    manyToOne:
        patient:
            targetEntity: Patient
            inversedBy: statuses
            joinColumn:
                name: patientId
                referencedColumnName: id
