Getunik\BleedHd\AssessmentDataBundle\Entity\Response:
    type:  entity
    table: Response
    repositoryClass: Getunik\BleedHd\AssessmentDataBundle\Entity\ResponseRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastUpdatedDate:
            type: datetimetz
            nullable: false
        lastUpdatedBy:
            type: integer
            nullable: false
        assessmentId:
            type: integer
            nullable: false
        questionSlug:
            type: string
            length: 255
            nullable: false
        result:
            type: json_array
            nullable: false
    manyToOne:
        assessment:
            targetEntity: Assessment
            inversedBy: responses
            joinColumn:
                name: assessmentId
                referencedColumnName: id
